/**
 * Crosswordese — a curated corpus of stock short answers and the clue
 * phrasings that conventionally point at them.
 *
 * Why this file exists: Datamuse answers "what words are semantically near
 * this phrase", which is the wrong question for a lot of crossword fill.
 * "Old coin" gives ANTIQUE and RELIC there, but the grid wants SOU — not
 * because a sou is *like* an old coin, but because decades of published
 * puzzles made it the convention. Association can't recover convention, so
 * the convention is written down here instead.
 *
 * Scope is deliberately narrow: the short, recurring fill (mostly 3–5
 * letters) where Datamuse is weakest and where crosswords repeat themselves
 * most. It is not, and cannot be, a general clue database.
 *
 * Shape, kept terse because it ships in the bundle:
 *   a — the answer in grid form (A–Z, uppercase)
 *   g — a one-line gloss, shown under the answer like a Datamuse definition
 *   c — stock clue phrasings, lowercased; matched by content-word overlap
 *
 * Adding entries: put the plainest clue first, then variants. A clue only
 * needs to contain the words a setter would use — the matcher handles word
 * order, plurals, and filler words.
 */

export interface CluedAnswer {
  a: string;
  g: string;
  c: string[];
}

export const CROSSWORDESE: CluedAnswer[] = [
  // --- Money, old and foreign -------------------------------------------
  { a: 'SOU', g: 'A former French coin of trifling value; a pittance.', c: ['old coin', 'old french coin', 'french coin', 'bit of old french change', 'coin of old france', 'small french coin'] },
  { a: 'ECU', g: 'An old French silver coin bearing a shield.', c: ['old coin', 'old french coin', 'french shield coin', 'pre-euro french coin'] },
  { a: 'ORE', g: 'A Scandinavian coin, one hundredth of a krona or krone.', c: ['old coin', 'scandinavian coin', 'norwegian coin', 'swedish coin', 'krona fraction', 'oslo coin'] },
  { a: 'OBOL', g: 'An ancient Greek coin worth one sixth of a drachma.', c: ['old coin', 'ancient greek coin', 'greek coin', 'charons fee'] },
  { a: 'GROAT', g: 'An old English silver fourpenny piece.', c: ['old coin', 'old english coin', 'english fourpence', 'small old sum'] },
  { a: 'DUCAT', g: 'A gold coin once used across much of Europe.', c: ['old coin', 'old european coin', 'venetian coin', 'gold coin of old'] },
  { a: 'FLORIN', g: 'An old gold coin of Florence; later a British two-shilling piece.', c: ['old coin', 'florentine coin', 'two shilling piece'] },
  { a: 'ANNA', g: 'A former coin of India and Pakistan, one sixteenth of a rupee.', c: ['old coin', 'old indian coin', 'rupee fraction', 'former indian coin'] },
  { a: 'REAL', g: 'An old Spanish silver coin; a piece of eight was worth eight of them.', c: ['old coin', 'old spanish coin', 'spanish coin', 'piece of eight part'] },
  { a: 'PESETA', g: 'The currency of Spain before the euro.', c: ['old coin', 'old spanish currency', 'pre-euro spanish money'] },
  { a: 'LIRA', g: 'The currency of Italy before the euro.', c: ['old coin', 'old italian currency', 'pre-euro italian money', 'turkish currency'] },
  { a: 'DINAR', g: 'The currency of several Middle Eastern and North African countries.', c: ['middle eastern currency', 'iraqi money', 'jordanian currency'] },
  { a: 'RIAL', g: 'The currency of Iran and Oman.', c: ['iranian currency', 'omani money', 'middle eastern money'] },
  { a: 'RAND', g: 'The currency of South Africa.', c: ['south african currency', 'pretoria money', 'johannesburg money'] },
  { a: 'KRONA', g: 'The currency of Sweden and Iceland.', c: ['swedish currency', 'stockholm money', 'nordic money'] },
  { a: 'PESO', g: 'The currency of Mexico and much of Latin America.', c: ['mexican money', 'latin american currency', 'manila money'] },
  { a: 'SEN', g: 'A small coin of Japan and parts of Southeast Asia.', c: ['old coin', 'japanese coin', 'yen fraction', 'small asian coin'] },
  { a: 'MITE', g: 'A coin of the very smallest value; a tiny contribution.', c: ['old coin', 'small coin', 'widows offering', 'tiny bit'] },
  { a: 'ANTE', g: 'The stake each player puts in the pot before a hand is dealt.', c: ['poker stake', 'pot starter', 'chip in', 'kitty contribution', 'opening bet'] },
  { a: 'INGOT', g: 'A mass of cast metal, usually a bar of gold or silver.', c: ['gold bar', 'bullion unit', 'cast metal bar', 'fort knox unit'] },

  // --- Rivers and waters -------------------------------------------------
  { a: 'ARNO', g: 'The river running through Florence and Pisa.', c: ['italian river', 'florence river', 'pisa river', 'river of tuscany'] },
  { a: 'EBRO', g: 'The longest river running entirely within Spain.', c: ['spanish river', 'river of spain', 'zaragoza river'] },
  { a: 'ODER', g: 'A central European river forming much of the Germany–Poland border.', c: ['european river', 'german river', 'polish border river'] },
  { a: 'ELBE', g: 'A river flowing from the Czech mountains through Hamburg to the North Sea.', c: ['german river', 'hamburg river', 'european river'] },
  { a: 'AMUR', g: 'A river along the border of Russia and China.', c: ['asian river', 'siberian river', 'russia china border river'] },
  { a: 'URAL', g: 'A Russian river, and the mountain range dividing Europe from Asia.', c: ['russian river', 'russian range', 'europe asia divider', 'mountain range'] },
  { a: 'AARE', g: 'The longest river entirely within Switzerland.', c: ['swiss river', 'bern river', 'river of switzerland'] },
  { a: 'ISERE', g: 'A French river flowing from the Alps into the Rhone.', c: ['french river', 'alpine river', 'rhone tributary'] },
  { a: 'SAAR', g: 'A river of France and Germany, and the German state named for it.', c: ['german river', 'french river', 'german state', 'moselle tributary'] },
  { a: 'YSER', g: 'A river of Belgium and France, and a First World War battle site.', c: ['belgian river', 'flanders river', 'wwi river'] },
  { a: 'OUSE', g: 'The name of several English rivers, including one in Yorkshire.', c: ['english river', 'yorkshire river', 'river of england'] },
  { a: 'EXE', g: 'A river of Devon, England, giving Exeter its name.', c: ['english river', 'devon river', 'exeter river'] },
  { a: 'AVON', g: 'An English river, famously Shakespeare’s at Stratford.', c: ['english river', 'stratford river', 'shakespeares river'] },
  { a: 'NILE', g: 'The great river of northeast Africa.', c: ['african river', 'egyptian river', 'longest river', 'cairo river'] },
  { a: 'TIBER', g: 'The river of Rome.', c: ['rome river', 'italian river', 'river of rome'] },
  { a: 'RHONE', g: 'A river flowing from the Alps through France to the Mediterranean.', c: ['french river', 'lyon river', 'alpine river'] },
  { a: 'SEINE', g: 'The river of Paris.', c: ['paris river', 'french river', 'river of paris'] },
  { a: 'ARAL', g: 'A once-vast inland sea in Central Asia, now largely dried up.', c: ['shrinking sea', 'asian sea', 'kazakhstan sea'] },
  { a: 'TARN', g: 'A small mountain lake in a glacial hollow.', c: ['mountain lake', 'small lake', 'glacial pool', 'alpine lake'] },
  { a: 'LOCH', g: 'A Scottish lake or narrow sea inlet.', c: ['scottish lake', 'ness for one', 'highland water'] },
  { a: 'FEN', g: 'Low, flat, marshy ground.', c: ['marsh', 'wetland', 'bog', 'swampy ground'] },
  { a: 'WEIR', g: 'A low dam built across a river to control its flow.', c: ['river dam', 'low dam', 'fish trap barrier'] },
  { a: 'SHOAL', g: 'A shallow place in a body of water; also a school of fish.', c: ['shallow spot', 'sandbar', 'fish group'] },
  { a: 'QUAY', g: 'A landing place built along the water where ships load.', c: ['wharf', 'dock', 'landing place', 'pier'] },
  { a: 'NEAP', g: 'The tide of least range, at the moon’s first and third quarters.', c: ['low tide', 'tide type', 'minimal tide', 'weak tide'] },
  { a: 'EDDY', g: 'A circular movement of water running against the main current.', c: ['swirl', 'whirlpool', 'current counterflow', 'water swirl'] },
  { a: 'ATOLL', g: 'A ring-shaped coral island enclosing a lagoon.', c: ['coral island', 'ring shaped reef', 'pacific island type', 'lagoon encircler'] },
  { a: 'SWALE', g: 'A low, moist tract of land.', c: ['marshy hollow', 'low ground', 'moist depression'] },

  // --- Peaks, places, and points on the map ------------------------------
  { a: 'ETNA', g: 'The active volcano on Sicily.', c: ['sicilian volcano', 'italian volcano', 'active volcano', 'catania backdrop'] },
  { a: 'OSSA', g: 'A mountain in Thessaly, piled on Pelion in Greek myth.', c: ['greek mountain', 'thessaly peak', 'pelion partner'] },
  { a: 'EIGER', g: 'A Swiss peak known for its formidable north face.', c: ['swiss peak', 'alpine mountain', 'bernese alps peak'] },
  { a: 'ARARAT', g: 'The Turkish mountain where the ark is said to have landed.', c: ['biblical mountain', 'turkish peak', 'ark landing site'] },
  { a: 'SINAI', g: 'The peninsula and mountain where Moses received the commandments.', c: ['biblical mountain', 'egyptian peninsula', 'commandments site'] },
  { a: 'TOR', g: 'A rocky peak or hill, especially on English moorland.', c: ['rocky peak', 'craggy hill', 'moorland outcrop', 'dartmoor feature'] },
  { a: 'MESA', g: 'A flat-topped hill with steep sides.', c: ['flat topped hill', 'southwest formation', 'arizona landform', 'plateau'] },
  { a: 'ADEN', g: 'The port city of Yemen.', c: ['yemeni port', 'gulf of arabia city', 'arabian port'] },
  { a: 'AGRA', g: 'The Indian city of the Taj Mahal.', c: ['taj mahal city', 'indian city', 'city on the yamuna'] },
  { a: 'OSLO', g: 'The capital of Norway.', c: ['norwegian capital', 'scandinavian capital', 'nobel peace prize city'] },
  { a: 'ELBA', g: 'The Mediterranean island of Napoleon’s first exile.', c: ['napoleons isle', 'exile island', 'tuscan island', 'mediterranean island'] },
  { a: 'EIRE', g: 'The Irish name for Ireland.', c: ['ireland once', 'emerald isle', 'irish name for ireland'] },
  { a: 'IONA', g: 'A small Scottish island with an ancient abbey.', c: ['scottish island', 'hebrides isle', 'abbey island'] },
  { a: 'ERIE', g: 'The shallowest of the Great Lakes; also a Pennsylvania port city.', c: ['great lake', 'lake by cleveland', 'canal name', 'pennsylvania port'] },
  { a: 'OAHU', g: 'The Hawaiian island where Honolulu sits.', c: ['hawaiian island', 'honolulu island', 'waikiki locale'] },
  { a: 'NOME', g: 'A town on Alaska’s Seward Peninsula, the end of the Iditarod.', c: ['alaskan town', 'iditarod finish', 'gold rush town'] },
  { a: 'RENO', g: 'The Nevada city that calls itself the biggest little city.', c: ['nevada city', 'gambling city', 'biggest little city'] },
  { a: 'ARLES', g: 'A city in Provence where Van Gogh painted.', c: ['french city', 'van gogh locale', 'provence city'] },
  { a: 'ESSEN', g: 'A city in Germany’s Ruhr industrial region.', c: ['german city', 'ruhr city', 'industrial german city'] },
  { a: 'THULE', g: 'The northernmost land known to the ancients; a Greenland base.', c: ['far north', 'greenland base', 'northern limit', 'ultima follower'] },
  { a: 'TYRE', g: 'An ancient Phoenician port city in Lebanon.', c: ['ancient port', 'phoenician city', 'lebanese city'] },
  { a: 'SIAM', g: 'The former name of Thailand.', c: ['thailand once', 'old asian kingdom', 'anna’s locale'] },
  { a: 'TARA', g: 'The O’Hara plantation in Gone with the Wind; a hill of ancient Irish kings.', c: ['gone with the wind estate', 'oharas home', 'irish hill of kings'] },
  { a: 'EDEN', g: 'The garden of Genesis; any place of unspoiled delight.', c: ['garden spot', 'paradise', 'biblical garden', 'first home'] },
  { a: 'ASIA', g: 'The largest continent.', c: ['largest continent', 'continent', 'east of the urals'] },

  // --- Myth and the classical world --------------------------------------
  { a: 'ARES', g: 'The Greek god of war, counterpart of Mars.', c: ['war god', 'greek god', 'mars counterpart', 'olympian'] },
  { a: 'EROS', g: 'The Greek god of love, counterpart of Cupid.', c: ['love god', 'greek god', 'cupid counterpart', 'archer of myth'] },
  { a: 'HERA', g: 'The queen of the Greek gods, wife of Zeus.', c: ['greek goddess', 'zeus wife', 'queen of olympus', 'juno counterpart'] },
  { a: 'EOS', g: 'The Greek goddess of the dawn.', c: ['dawn goddess', 'greek goddess', 'aurora counterpart', 'morning deity'] },
  { a: 'ATE', g: 'The Greek goddess of ruin, folly, and reckless impulse.', c: ['greek goddess', 'goddess of folly', 'mischief goddess', 'ruin personified'] },
  { a: 'RHEA', g: 'A Titaness, mother of Zeus; also a large flightless South American bird.', c: ['greek goddess', 'titaness', 'zeus mother', 'flightless bird', 'ostrich relative'] },
  { a: 'HEBE', g: 'The Greek goddess of youth, cupbearer to the gods.', c: ['greek goddess', 'youth goddess', 'olympian cupbearer'] },
  { a: 'LETO', g: 'The mother of Apollo and Artemis.', c: ['greek goddess', 'apollos mother', 'artemis mother'] },
  { a: 'IRIS', g: 'The Greek goddess of the rainbow; also the coloured part of the eye and a flower.', c: ['rainbow goddess', 'greek goddess', 'eye part', 'spring flower', 'messenger of the gods'] },
  { a: 'NIKE', g: 'The Greek goddess of victory.', c: ['victory goddess', 'greek goddess', 'winged deity'] },
  { a: 'ECHO', g: 'The nymph who could only repeat what others said.', c: ['greek nymph', 'repeated sound', 'narcissus admirer', 'canyon sound'] },
  { a: 'ODIN', g: 'The chief god of Norse mythology.', c: ['norse god', 'thors father', 'chief of the aesir', 'valhalla ruler'] },
  { a: 'THOR', g: 'The Norse god of thunder, wielder of the hammer.', c: ['norse god', 'thunder god', 'hammer wielder', 'odins son'] },
  { a: 'LOKI', g: 'The trickster god of Norse mythology.', c: ['norse god', 'trickster god', 'mischief maker of myth'] },
  { a: 'ISIS', g: 'The Egyptian goddess of magic and motherhood.', c: ['egyptian goddess', 'osiris wife', 'horus mother'] },
  { a: 'THOTH', g: 'The ibis-headed Egyptian god of writing and wisdom.', c: ['egyptian god', 'ibis headed god', 'god of scribes'] },
  { a: 'AMON', g: 'A chief Egyptian deity, often joined with Ra.', c: ['egyptian god', 'ra partner', 'theban deity'] },
  { a: 'ICHOR', g: 'The fluid said to flow in the veins of the gods.', c: ['blood of the gods', 'divine fluid', 'mythical blood'] },
  { a: 'STOA', g: 'A covered colonnade in ancient Greek architecture.', c: ['greek colonnade', 'ancient portico', 'covered walkway', 'athens structure'] },
  { a: 'APSE', g: 'The vaulted semicircular recess at the end of a church.', c: ['church recess', 'cathedral part', 'vaulted alcove', 'chancel end'] },
  { a: 'TOGA', g: 'The draped outer garment of a Roman citizen.', c: ['roman garment', 'ancient wrap', 'frat party wear', 'caesars wear'] },
  { a: 'IDES', g: 'The fifteenth of March, May, July, and October in the Roman calendar.', c: ['roman date', 'caesars downfall day', 'march date', 'calendar division'] },
  { a: 'ESNE', g: 'A labourer or household slave in Anglo-Saxon England.', c: ['anglo saxon laborer', 'old english serf', 'medieval servant'] },
  { a: 'THANE', g: 'A man holding land from a Scottish or Anglo-Saxon lord.', c: ['scottish lord', 'macbeth title', 'anglo saxon noble', 'cawdor for one'] },
  { a: 'ORLE', g: 'A narrow border set in from the edge of a heraldic shield.', c: ['heraldic border', 'shield band', 'coat of arms edge'] },

  // --- Greek letters ------------------------------------------------------
  { a: 'ETA', g: 'The seventh letter of the Greek alphabet.', c: ['greek letter', 'seventh greek letter', 'arrival estimate'] },
  { a: 'IOTA', g: 'The ninth Greek letter; by extension, the smallest possible amount.', c: ['greek letter', 'tiny bit', 'jot', 'smallest amount', 'whit'] },
  { a: 'RHO', g: 'The seventeenth letter of the Greek alphabet.', c: ['greek letter', 'p in greek', 'correlation symbol'] },
  { a: 'PHI', g: 'The Greek letter used for the golden ratio.', c: ['greek letter', 'golden ratio symbol', 'frat letter'] },
  { a: 'CHI', g: 'The twenty-second Greek letter, used in a statistical test.', c: ['greek letter', 'square starter in stats', 'frat letter'] },
  { a: 'PSI', g: 'The Greek letter used as a symbol for the mind.', c: ['greek letter', 'psychology symbol', 'trident shaped letter'] },
  { a: 'TAU', g: 'The nineteenth letter of the Greek alphabet.', c: ['greek letter', 't in greek', 'frat letter'] },
  { a: 'BETA', g: 'The second Greek letter; a pre-release version of software.', c: ['greek letter', 'second greek letter', 'test version', 'software stage'] },
  { a: 'ZETA', g: 'The sixth letter of the Greek alphabet.', c: ['greek letter', 'sixth greek letter'] },
  { a: 'THETA', g: 'The eighth Greek letter, often used for an angle.', c: ['greek letter', 'angle symbol', 'eighth greek letter'] },
  { a: 'OMEGA', g: 'The last letter of the Greek alphabet; the end.', c: ['greek letter', 'last greek letter', 'the end', 'alpha partner', 'watch brand'] },
  { a: 'ALPHA', g: 'The first letter of the Greek alphabet; the dominant one.', c: ['greek letter', 'first greek letter', 'top dog', 'beginning'] },
  { a: 'SIGMA', g: 'The Greek letter used to denote a sum.', c: ['greek letter', 'summation symbol', 'math sum sign'] },

  // --- Names that keep coming back ---------------------------------------
  { a: 'ENO', g: 'Brian Eno, the producer who named ambient music.', c: ['brian of ambient music', 'music producer', 'ambient pioneer', 'roxy music alum'] },
  { a: 'ONO', g: 'Yoko Ono, artist and musician.', c: ['yoko of the beatles circle', 'lennons widow', 'conceptual artist'] },
  { a: 'ASTA', g: 'The wire fox terrier in the Thin Man films.', c: ['thin man dog', 'movie dog', 'nick and noras dog', 'film terrier'] },
  { a: 'ODIE', g: 'The drooling dog in the Garfield comic strip.', c: ['garfield dog', 'comic strip dog', 'cartoon canine'] },
  { a: 'OPIE', g: 'The boy in The Andy Griffith Show, played by Ron Howard.', c: ['mayberry boy', 'andy griffith son', 'ron howard role'] },
  { a: 'ORR', g: 'Bobby Orr, the Bruins defenceman who changed the position.', c: ['bobby of the bruins', 'hockey great', 'bruins legend'] },
  { a: 'ELIA', g: 'Charles Lamb’s pen name; also director Elia Kazan.', c: ['lambs pen name', 'kazan of film', 'essayist pseudonym'] },
  { a: 'ETTA', g: 'Etta James, the singer of "At Last".', c: ['singer james', 'at last singer', 'blues singer'] },
  { a: 'ENYA', g: 'The Irish singer of layered, wordless vocals.', c: ['irish singer', 'orinoco flow singer', 'new age musician'] },
  { a: 'UMA', g: 'Uma Thurman, the actor.', c: ['thurman of film', 'kill bill star', 'actress thurman'] },
  { a: 'ARLO', g: 'Arlo Guthrie, the folk singer.', c: ['guthrie the younger', 'folk singer', 'alices restaurant singer'] },
  { a: 'ESAU', g: 'Isaac’s elder son, who sold his birthright to Jacob.', c: ['biblical twin', 'jacobs brother', 'birthright seller', 'isaacs son'] },
  { a: 'ELI', g: 'The priest who raised Samuel; also quarterback Eli Manning.', c: ['biblical priest', 'samuels mentor', 'manning of football', 'whitney of the cotton gin'] },
  { a: 'AMOS', g: 'A minor prophet of the Hebrew Bible.', c: ['biblical prophet', 'minor prophet', 'andy partner in old radio'] },
  { a: 'EZRA', g: 'The scribe who led the return from Babylon; also poet Ezra Pound.', c: ['biblical scribe', 'poet pound', 'old testament book'] },
  { a: 'LEAH', g: 'Jacob’s first wife, elder sister of Rachel.', c: ['jacobs wife', 'rachels sister', 'biblical wife'] },
  { a: 'ABEL', g: 'Adam’s second son, killed by Cain.', c: ['cains brother', 'first victim', 'adams son'] },
  { a: 'MOAB', g: 'An ancient kingdom east of the Dead Sea; a Utah town.', c: ['biblical kingdom', 'utah town', 'ancient land'] },
  { a: 'AVA', g: 'Ava Gardner, the actor.', c: ['gardner of film', 'actress gardner', 'old hollywood star'] },
  { a: 'IDA', g: 'A Cretan mountain; also actor Ida Lupino.', c: ['cretan mountain', 'lupino of film', 'womans name'] },
  { a: 'OLAF', g: 'The name of several Norwegian kings; also the Frozen snowman.', c: ['norwegian king', 'frozen snowman', 'nordic name'] },
  { a: 'OTTO', g: 'A palindromic name borne by Holy Roman emperors.', c: ['palindromic name', 'german emperor', 'bus driver of the simpsons'] },
  { a: 'ERLE', g: 'Erle Stanley Gardner, creator of Perry Mason.', c: ['gardner of mysteries', 'perry mason creator', 'writer stanley gardner'] },
  { a: 'ENID', g: 'A city in Oklahoma; also novelist Enid Blyton.', c: ['oklahoma city', 'blyton of childrens books', 'womans name'] },
  { a: 'IVAN', g: 'The name of several Russian tsars, one of them Terrible.', c: ['russian tsar', 'terrible ruler', 'russian name'] },

  // --- Music, art, and the stage ------------------------------------------
  { a: 'ARIA', g: 'A solo song in an opera.', c: ['opera solo', 'diva number', 'opera song', 'solo piece'] },
  { a: 'CODA', g: 'The closing passage of a piece of music.', c: ['closing passage', 'musical ending', 'finale', 'concluding section'] },
  { a: 'OPUS', g: 'A numbered musical work.', c: ['musical work', 'composition', 'numbered piece', 'magnum follower'] },
  { a: 'ETUDE', g: 'A short piece written to practise a technique.', c: ['practice piece', 'music study', 'chopin work', 'piano exercise'] },
  { a: 'LARGO', g: 'A slow, broad tempo marking.', c: ['slow tempo', 'music direction', 'broadly in music'] },
  { a: 'LENTO', g: 'A slow tempo marking.', c: ['slow tempo', 'music direction', 'slowly in scores'] },
  { a: 'RONDO', g: 'A musical form in which the main theme keeps returning.', c: ['musical form', 'recurring theme piece', 'sonata finale form'] },
  { a: 'MOTET', g: 'A sacred choral composition, usually unaccompanied.', c: ['choral work', 'sacred piece', 'church composition'] },
  { a: 'SEGNO', g: 'The sign in a score marking a repeat point.', c: ['score sign', 'repeat mark', 'dal follower'] },
  { a: 'OBOE', g: 'A double-reed woodwind instrument.', c: ['woodwind', 'double reed', 'orchestra tuner', 'reed instrument'] },
  { a: 'LYRE', g: 'A small harp-like instrument of the ancient world.', c: ['ancient harp', 'orpheus instrument', 'greek instrument', 'apollos instrument'] },
  { a: 'LUTE', g: 'A plucked string instrument with a pear-shaped body.', c: ['old string instrument', 'renaissance instrument', 'minstrels instrument'] },
  { a: 'VIOL', g: 'An early bowed string instrument played upright.', c: ['old string instrument', 'baroque instrument', 'da gamba instrument'] },
  { a: 'ALTO', g: 'The voice or range below soprano.', c: ['choir voice', 'singing range', 'sax type', 'between tenor and soprano'] },
  { a: 'ODE', g: 'A lyric poem addressed to its subject.', c: ['lyric poem', 'keats work', 'poem of praise', 'tribute in verse'] },
  { a: 'ELEGY', g: 'A poem of mourning.', c: ['mournful poem', 'lament', 'poem of loss', 'grays work'] },
  { a: 'TEMPO', g: 'The speed at which music is played.', c: ['music speed', 'pace', 'metronome setting'] },

  // --- The classic short fill ---------------------------------------------
  { a: 'OLEO', g: 'Margarine, as a butter substitute.', c: ['butter substitute', 'margarine', 'spread', 'table spread'] },
  { a: 'OLIO', g: 'A miscellaneous collection; a hodgepodge.', c: ['medley', 'hodgepodge', 'mixture', 'miscellany', 'potpourri'] },
  { a: 'ETUI', g: 'A small ornamental case for needles or small tools.', c: ['small case', 'needle case', 'sewing kit holder', 'trinket box'] },
  { a: 'ADIT', g: 'A horizontal entrance to a mine.', c: ['mine entrance', 'mine shaft', 'tunnel entrance', 'horizontal passage'] },
  { a: 'EPEE', g: 'The heaviest of the three fencing swords.', c: ['fencing sword', 'fencing blade', 'olympic weapon', 'duelers choice'] },
  { a: 'ELAN', g: 'Vigorous spirit; dash and style.', c: ['dash', 'verve', 'flair', 'zest', 'spirited style'] },
  { a: 'ANIL', g: 'The indigo plant, and the dye made from it.', c: ['indigo plant', 'blue dye', 'dye source', 'indigo source'] },
  { a: 'ALEE', g: 'On the side away from the wind.', c: ['away from the wind', 'sheltered side', 'nautical direction', 'leeward'] },
  { a: 'AVAST', g: 'A nautical command to stop.', c: ['nautical stop', 'sailors halt', 'pirate command', 'hold it at sea'] },
  { a: 'ADZE', g: 'A tool like an axe with the blade set crosswise, for shaping wood.', c: ['shaping tool', 'wood tool', 'axe relative', 'coopers tool'] },
  { a: 'AWL', g: 'A pointed tool for piercing holes in leather or wood.', c: ['piercing tool', 'leather tool', 'cobblers tool', 'hole maker'] },
  { a: 'SNEE', g: 'To cut; also a dagger, chiefly in the phrase snick and snee.', c: ['cut', 'dagger', 'snick partner', 'old blade'] },
  { a: 'EWER', g: 'A wide-mouthed pitcher for water.', c: ['pitcher', 'water jug', 'basin companion', 'washstand vessel'] },
  { a: 'OAST', g: 'A kiln for drying hops.', c: ['hop kiln', 'drying kiln', 'brewery oven', 'kentish structure'] },
  { a: 'ORT', g: 'A scrap of food left after a meal.', c: ['table scrap', 'food bit', 'leftover morsel', 'crumb'] },
  { a: 'AERIE', g: 'The nest of a bird of prey, built high up.', c: ['eagles nest', 'high nest', 'birds perch', 'lofty home'] },
  { a: 'ERNE', g: 'A sea eagle.', c: ['sea eagle', 'shore bird', 'eagle', 'coastal raptor'] },
  { a: 'ANOA', g: 'A small wild ox of Sulawesi.', c: ['wild ox', 'celebes ox', 'small buffalo', 'indonesian bovine'] },
  { a: 'ELAND', g: 'The largest African antelope, with spiral horns.', c: ['african antelope', 'large antelope', 'spiral horned beast', 'safari sight'] },
  { a: 'GNU', g: 'The wildebeest, an African antelope with a heavy head.', c: ['african antelope', 'wildebeest', 'safari animal', 'horned grazer'] },
  { a: 'OKAPI', g: 'A short-necked relative of the giraffe with striped legs.', c: ['giraffe relative', 'african mammal', 'striped legged beast', 'zoo attraction'] },
  { a: 'ZEBU', g: 'A humped ox of South Asia.', c: ['humped ox', 'asian cattle', 'brahman relative', 'indian cow'] },
  { a: 'IBEX', g: 'A wild mountain goat with long curved horns.', c: ['wild goat', 'mountain goat', 'horned climber', 'alpine animal'] },
  { a: 'IBIS', g: 'A long-legged wading bird with a curved bill.', c: ['wading bird', 'egyptian bird', 'curved bill bird', 'marsh bird'] },
  { a: 'EGRET', g: 'A white heron with long plumes.', c: ['wading bird', 'white heron', 'marsh bird', 'plumed bird'] },
  { a: 'TERN', g: 'A slender seabird with a forked tail.', c: ['sea bird', 'gull relative', 'shore bird', 'forked tail flier'] },
  { a: 'WREN', g: 'A tiny brown songbird; also architect Christopher Wren.', c: ['small bird', 'tiny songbird', 'st pauls architect', 'little bird'] },
  { a: 'ORCA', g: 'The killer whale.', c: ['killer whale', 'sea mammal', 'black and white whale', 'seaworld star'] },
  { a: 'ROAN', g: 'A horse whose coat is flecked with white.', c: ['horse color', 'flecked horse', 'coat pattern', 'speckled steed'] },
  { a: 'SLOE', g: 'The small blue-black fruit of the blackthorn.', c: ['blackthorn fruit', 'gin flavoring', 'tart fruit', 'small plum'] },
  { a: 'ALOE', g: 'A succulent plant whose gel soothes burns.', c: ['soothing plant', 'burn soother', 'succulent', 'lotion ingredient'] },
  { a: 'AGAR', g: 'A jelly from seaweed used to grow laboratory cultures.', c: ['lab gel', 'culture medium', 'seaweed extract', 'petri dish filler'] },
  { a: 'ARIL', g: 'The fleshy covering of some seeds.', c: ['seed covering', 'pomegranate part', 'fleshy seed coat'] },
  { a: 'SUMAC', g: 'A shrub with red fruit clusters; some species cause a rash.', c: ['shrub', 'poison plant', 'red spice', 'rash causer'] },
  { a: 'TARO', g: 'A tropical root eaten as a staple, the source of poi.', c: ['poi source', 'root vegetable', 'tropical tuber', 'hawaiian staple'] },
  { a: 'EDAM', g: 'A mild Dutch cheese sold in a red wax rind.', c: ['dutch cheese', 'waxed cheese', 'mild cheese', 'red rinded cheese'] },
  { a: 'SUET', g: 'Hard animal fat used in cooking and bird feed.', c: ['cooking fat', 'pudding fat', 'bird feed', 'hard fat'] },
  { a: 'ROE', g: 'Fish eggs.', c: ['fish eggs', 'caviar', 'sushi topping', 'shad delicacy'] },
  { a: 'GHEE', g: 'Clarified butter used in Indian cooking.', c: ['clarified butter', 'indian butter', 'cooking fat'] },
  { a: 'NAAN', g: 'A soft flatbread baked in a tandoor.', c: ['indian bread', 'flatbread', 'tandoor bread', 'curry accompaniment'] },
  { a: 'MISO', g: 'A savoury paste of fermented soybeans.', c: ['soup base', 'japanese paste', 'fermented soybean paste'] },
  { a: 'SAKE', g: 'Japanese rice wine.', c: ['rice wine', 'japanese drink', 'warm beverage'] },
  { a: 'PILAF', g: 'Rice cooked in seasoned stock.', c: ['rice dish', 'seasoned rice', 'side dish'] },
  { a: 'OGEE', g: 'A moulding with an S-shaped profile.', c: ['s curve', 'architectural molding', 'double curve', 'arch shape'] },
  { a: 'NEWEL', g: 'The central post of a staircase, or the post at its foot.', c: ['staircase post', 'banister support', 'stair part'] },
  { a: 'EAVE', g: 'The overhanging lower edge of a roof.', c: ['roof edge', 'overhang', 'roof part', 'icicle site'] },
  { a: 'MOAT', g: 'A defensive ditch of water round a castle.', c: ['castle ditch', 'defensive water', 'drawbridge crossing', 'fortification'] },
  { a: 'KILN', g: 'An oven for firing pottery or drying timber.', c: ['pottery oven', 'firing furnace', 'ceramics oven', 'brick baker'] },
  { a: 'SILO', g: 'A tower for storing grain, or an underground missile housing.', c: ['grain tower', 'farm structure', 'missile housing', 'storage tower'] },
  { a: 'URN', g: 'A tall vase, sometimes holding ashes or coffee.', c: ['vase', 'ashes holder', 'coffee dispenser', 'grecian vessel'] },
  { a: 'VIAL', g: 'A small glass container for liquids.', c: ['small bottle', 'lab container', 'sample holder', 'medicine bottle'] },
  { a: 'VANE', g: 'A blade turned by wind or water; a weathercock.', c: ['weather indicator', 'wind indicator', 'rooftop rooster', 'turbine blade'] },
  { a: 'KEEL', g: 'The timber running along the bottom of a boat.', c: ['boat bottom', 'ship part', 'hull spine', 'even follower'] },
  { a: 'DHOW', g: 'A lateen-rigged sailing vessel of the Arabian Sea.', c: ['arab boat', 'sailing vessel', 'indian ocean craft'] },
  { a: 'YAWL', g: 'A two-masted sailing boat with a small mizzen aft.', c: ['sailboat', 'two masted boat', 'small vessel'] },
  { a: 'SPAR', g: 'A pole supporting a ship’s sail; also to box lightly.', c: ['mast', 'ship pole', 'box lightly', 'practice fight'] },
  { a: 'MIEN', g: 'A person’s look or bearing.', c: ['bearing', 'demeanor', 'air', 'appearance', 'manner'] },
  { a: 'ILK', g: 'A type or kind.', c: ['sort', 'kind', 'type', 'variety'] },
  { a: 'ONUS', g: 'A burden or responsibility.', c: ['burden', 'responsibility', 'obligation', 'load'] },
  { a: 'ADO', g: 'Fuss and bother.', c: ['fuss', 'bother', 'to do', 'commotion', 'much of nothing'] },
  { a: 'SNIT', g: 'A fit of irritation.', c: ['huff', 'fit of temper', 'irritated state', 'tizzy'] },
  { a: 'RUNE', g: 'A character of the old Germanic alphabet, often thought magical.', c: ['old letter', 'norse character', 'mystic symbol', 'viking writing'] },
  { a: 'TROVE', g: 'A store of valuable things discovered.', c: ['hoard', 'valuable find', 'treasure', 'cache'] },
  { a: 'LOAM', g: 'Rich soil of sand, silt, and clay.', c: ['rich soil', 'garden soil', 'fertile earth'] },
  { a: 'CAIRN', g: 'A mound of stones raised as a marker; also a small terrier.', c: ['stone pile', 'trail marker', 'rock mound', 'small terrier'] },
  { a: 'BRAE', g: 'A hillside, in Scottish usage.', c: ['scottish hillside', 'slope', 'hill in scotland'] },
  { a: 'SERE', g: 'Dry and withered.', c: ['dry', 'withered', 'parched', 'arid'] },
  { a: 'ARID', g: 'So dry that little grows.', c: ['dry', 'parched', 'desert like', 'rainless'] },
  { a: 'AJAR', g: 'Slightly open.', c: ['partly open', 'slightly open', 'not quite shut', 'open a crack'] },
  { a: 'AGOG', g: 'Full of eager anticipation.', c: ['eager', 'excited', 'all agog', 'keenly expectant'] },
  { a: 'AWRY', g: 'Off course; not as intended.', c: ['off course', 'askew', 'gone wrong', 'crooked'] },
  { a: 'ANEW', g: 'Once more, from the start.', c: ['again', 'afresh', 'once more', 'from scratch'] },
  { a: 'ABET', g: 'To help or encourage, usually in wrongdoing.', c: ['help in crime', 'assist', 'aid partner', 'encourage'] },
  { a: 'AVER', g: 'To state as a fact.', c: ['assert', 'declare', 'state firmly', 'claim'] },
  { a: 'OUST', g: 'To drive out of a position.', c: ['expel', 'depose', 'remove from office', 'kick out'] },
  { a: 'SATE', g: 'To satisfy fully.', c: ['satisfy fully', 'fill up', 'glut', 'quench'] },
  { a: 'TEEM', g: 'To be full to overflowing.', c: ['abound', 'swarm', 'be full of', 'overflow'] },
  { a: 'ETCH', g: 'To cut a design into a surface with acid.', c: ['engrave', 'cut into glass', 'acid art', 'incise'] },
  { a: 'INURE', g: 'To harden by long exposure.', c: ['harden', 'accustom', 'toughen', 'habituate'] },
  { a: 'EMEND', g: 'To correct a text.', c: ['correct a text', 'edit', 'revise', 'fix copy'] },
  { a: 'CEDE', g: 'To give up, especially territory.', c: ['give up', 'yield', 'hand over', 'surrender'] },
  { a: 'DIRE', g: 'Dreadful; urgently serious.', c: ['grave', 'dreadful', 'urgent', 'terrible'] },
  { a: 'DOUR', g: 'Stern and forbidding.', c: ['stern', 'gloomy', 'grim', 'sullen'] },
  { a: 'GLIB', g: 'Fluent but insincere.', c: ['smooth talking', 'facile', 'slick', 'insincerely fluent'] },
  { a: 'IRATE', g: 'Very angry.', c: ['angry', 'furious', 'incensed', 'hopping mad'] },
  { a: 'INEPT', g: 'Clumsy and unskilled.', c: ['clumsy', 'bungling', 'unskilled', 'incompetent'] },
  { a: 'MOOT', g: 'Debatable, or made irrelevant by events.', c: ['debatable', 'academic', 'beside the point', 'arguable'] },
  { a: 'RIFE', g: 'Widespread, usually of something bad.', c: ['widespread', 'prevalent', 'abundant', 'common'] },
  { a: 'STAID', g: 'Sedate and unadventurous.', c: ['sedate', 'sober', 'unadventurous', 'stuffy'] },
  { a: 'SUAVE', g: 'Smooth and confident in manner.', c: ['smooth', 'polished', 'debonair', 'urbane'] },
  { a: 'TERSE', g: 'Brief to the point of curtness.', c: ['curt', 'brief', 'to the point', 'concise'] },
  { a: 'TEPID', g: 'Lukewarm, in temperature or enthusiasm.', c: ['lukewarm', 'unenthusiastic', 'mildly warm', 'halfhearted'] },
  { a: 'WILY', g: 'Cunning.', c: ['crafty', 'cunning', 'sly', 'foxy'] },
  { a: 'WRY', g: 'Drily humorous, with a twist.', c: ['drily humorous', 'twisted', 'ironic', 'sardonic'] },
  { a: 'WANE', g: 'To decrease, as the moon after full.', c: ['decrease', 'diminish', 'moon phase', 'dwindle'] },
  { a: 'EERIE', g: 'Strange and frightening.', c: ['spooky', 'uncanny', 'weird', 'ghostly'] },
  { a: 'NIGH', g: 'Near, in time or place.', c: ['near', 'close at hand', 'approaching', 'almost'] },
  { a: 'ASEA', g: 'Out on the water; at a loss.', c: ['on the water', 'at sea', 'adrift', 'confused'] },
  { a: 'AGUE', g: 'A fever with fits of shivering.', c: ['fever', 'chills', 'malarial fever', 'shivering fit'] },
  { a: 'STYE', g: 'An inflamed swelling on the eyelid.', c: ['eye problem', 'eyelid swelling', 'lid inflammation'] },
  { a: 'AMAH', g: 'A nurse or maid in East and South Asia.', c: ['eastern nurse', 'asian maid', 'nursemaid abroad'] },
  { a: 'SARI', g: 'A length of cloth draped as a dress in South Asia.', c: ['indian garment', 'draped dress', 'delhi wrap'] },
  { a: 'YURT', g: 'A portable round tent of the Central Asian steppes.', c: ['nomads tent', 'round dwelling', 'mongolian home', 'portable shelter'] },
  { a: 'EMIR', g: 'A ruler or commander in parts of the Muslim world.', c: ['arab ruler', 'middle eastern leader', 'gulf state ruler', 'sheikh kin'] },
  { a: 'TREY', g: 'A three in cards or dice; a three-pointer in basketball.', c: ['card three', 'dice roll', 'three pointer', 'three in cards'] },
  { a: 'FARO', g: 'A card game of the old American West.', c: ['old card game', 'saloon game', 'gambling game'] },
  { a: 'LOO', g: 'An old card game; also British slang for the lavatory.', c: ['old card game', 'british bathroom', 'water closet'] },
  { a: 'PONE', g: 'The non-dealer in cribbage; also corn bread.', c: ['cribbage player', 'corn bread', 'non dealer'] },
  { a: 'MELD', g: 'To declare a scoring combination of cards; to blend.', c: ['card combination', 'blend', 'rummy move', 'merge'] },
  { a: 'ESE', g: 'A compass point between east and southeast.', c: ['compass point', 'compass reading', 'map direction'] },
  { a: 'ENE', g: 'A compass point between east and northeast.', c: ['compass point', 'compass reading', 'map direction'] },
  { a: 'ELL', g: 'An old cloth measure of about 45 inches; a wing at right angles to a building.', c: ['old measure', 'cloth measure', 'building wing', 'l shaped addition'] },
  { a: 'ACME', g: 'The highest point.', c: ['peak', 'summit', 'highest point', 'zenith', 'pinnacle'] },
  { a: 'EPOCH', g: 'A long, distinct period of time.', c: ['era', 'age', 'period', 'time span'] },

  // --- Worship, and things worshipped -------------------------------------
  { a: 'IDOL', g: 'An image or object worshipped as a god; anyone adored.', c: ['false god', 'object of worship', 'graven image', 'teen heartthrob', 'american follower'] },
  { a: 'BAAL', g: 'An ancient Semitic deity, denounced as a false god in the Bible.', c: ['false god', 'biblical idol', 'ancient semitic god', 'canaanite deity'] },
  { a: 'ARK', g: 'Noah’s vessel; also the chest holding the Torah scrolls.', c: ['noahs vessel', 'biblical boat', 'covenant holder', 'flood craft'] },
  { a: 'AMEN', g: 'The word closing a prayer; an expression of assent.', c: ['prayer ending', 'end of a prayer', 'so be it', 'word of assent'] },
  { a: 'OMEN', g: 'A sign of what is to come.', c: ['sign', 'portent', 'augury', 'foreboding sign', 'harbinger'] },

  // --- Three and four letters, everywhere ---------------------------------
  { a: 'ASP', g: 'A small venomous snake of Egypt.', c: ['egyptian snake', 'cleopatras undoing', 'nile serpent', 'venomous snake'] },
  { a: 'EMU', g: 'A large flightless Australian bird.', c: ['flightless bird', 'australian bird', 'ostrich relative', 'big bird down under'] },
  { a: 'EEL', g: 'A long snakelike fish.', c: ['slippery fish', 'sushi fish', 'elver when young', 'long fish'] },
  { a: 'OAR', g: 'A pole with a blade, used to row a boat.', c: ['rowing tool', 'boat propeller', 'crew implement', 'rowers need'] },
  { a: 'APE', g: 'A tailless primate; also to imitate.', c: ['mimic', 'primate', 'imitate', 'copy', 'gorilla for one'] },
  { a: 'ANT', g: 'A small social insect.', c: ['picnic pest', 'colony member', 'small insect', 'worker in a colony'] },
  { a: 'ERR', g: 'To make a mistake.', c: ['slip up', 'make a mistake', 'goof', 'blunder', 'be wrong'] },
  { a: 'IRE', g: 'Anger.', c: ['anger', 'wrath', 'fury', 'rage', 'dander'] },
  { a: 'EON', g: 'An immeasurably long period of time.', c: ['long time', 'age', 'geologic span', 'ages and ages'] },
  { a: 'AWE', g: 'Reverential wonder.', c: ['wonder', 'reverence', 'amazement', 'shock partner'] },
  { a: 'EWE', g: 'A female sheep.', c: ['female sheep', 'rams mate', 'lamb bearer', 'flock member'] },
  { a: 'DOE', g: 'A female deer.', c: ['female deer', 'bambis mother', 'buck mate', 'forest female'] },
  { a: 'ALE', g: 'A beer brewed by warm fermentation.', c: ['pub drink', 'brew', 'tavern order', 'pint of bitter'] },
  { a: 'OAF', g: 'A clumsy, stupid person.', c: ['lout', 'clod', 'clumsy sort', 'boor', 'lummox'] },
  { a: 'ODOR', g: 'A smell, usually an unpleasant one.', c: ['smell', 'scent', 'stench', 'whiff'] },
  { a: 'ACHE', g: 'A dull continuous pain; to long for.', c: ['dull pain', 'throb', 'long for', 'yearn', 'hurt'] },
  { a: 'ACRE', g: 'A measure of land, 4,840 square yards.', c: ['land measure', 'farm unit', 'plot measure', 'field unit'] },
  { a: 'APEX', g: 'The very top.', c: ['peak', 'summit', 'top point', 'vertex', 'high point'] },
  { a: 'EDIT', g: 'To prepare text by correcting and cutting.', c: ['revise', 'blue pencil', 'prepare copy', 'cut and correct'] },
  { a: 'OMIT', g: 'To leave out.', c: ['leave out', 'skip', 'drop', 'pass over'] },
  { a: 'TSAR', g: 'An emperor of Russia; a person with sweeping authority.', c: ['russian ruler', 'russian emperor', 'kremlin figure of old', 'drug official'] },
  { a: 'ANON', g: 'Soon; also short for an unknown author.', c: ['soon', 'shortly', 'before long', 'unknown author'] },
  { a: 'ESPY', g: 'To catch sight of.', c: ['catch sight of', 'spot', 'glimpse', 'descry'] },
  { a: 'ETON', g: 'The English school that has schooled many prime ministers.', c: ['english school', 'british prep school', 'windsor school', 'harrow rival'] },
];
